### ISSUE TITLE
CSS style "position:absolute" makes paymill_subscription.html unusable

### ISSUE THREAD

**Issue by fabianwabbel** [paymill/paymill-payment-form#15]
If position:absolute is set on labels and input elements, paymill_subscription.html becomes unusable (see screenshot), paymill_payment.html looks fine. 
If removed paymill_subscription.html looks fine but paymill_payment.html breaks.

![paymill_payment html - without position absolute](https://f.cloud.github.com/assets/3736412/1921489/92445314-7dfa-11e3-8e37-f0c75d7fbfaa.png)
![paymill_subscription html - with position absolute](https://f.cloud.github.com/assets/3736412/1921490/924727a6-7dfa-11e3-83a7-f2be07a380f0.png)

**Comment by paymill-support** [comment]
Please enter your answer above the separator

Request received: [paymill-payment-form] CSS style "position:absolute" makes paymill_subscription.html unusable (#15) (Ticket Nr. #26257)

Hello paymill/paymill-payment-form!

Thank you for your request and interest in PAYMILL! 

We are very happy to help you and will get back to you within 24hours.

We have a FAQ section on our website you can look up in the meantime - https://paymill.zendesk.com/hc/en-us

Also we value any kind of comments or concerns, if you are up for a chat or discussion, please follow us on twitter www.twitter.com/paymill and Facebook www.facebook.com/paymill or have a look into our blog at https://blog.paymill.com/.

For updates on operations (such as our maintenance schedule) please look up https://twitter.com/PAYMILLOps.

Best

The PAYMILL Team

###

## https://support.paymill.com/hc/requests/26257

paymill/paymill-payment-form, Jan 15 16:37

If position:absolute is set on labels and input elements, paymill_subscription.html becomes unusable (see screenshot), paymill_payment.html looks fine. 
If removed paymill_subscription.html looks fine but paymill_payment.html breaks.

![paymill_payment html - without position absolute](https://f.cloud.github.com/assets/3736412/1921489/92445314-7dfa-11e3-8e37-f0c75d7fbfaa.png)
![paymill_subscription html - with position absolute](https://f.cloud.github.com/assets/3736412/1921490/924727a6-7dfa-11e3-83a7-f2be07a380f0.png)

---

Reply to this email directly or view it on GitHub:
https://github.com/paymill/paymill-payment-form/issues/15

---

This email is a service from PAYMILL GmbH Support.

[T665-G60P]

**Comment by enesf** [comment]
Stefan please take a look at this.

**Comment by enesf** [comment]
Reassigned to Thilo.

**Comment by enesf** [comment]
Reassigned to Stefan.
