### ISSUE TITLE
SEPA Example not working

### ISSUE THREAD

**Issue by stoilkov** [paymill/paymill-payment-form#17]
http://htmlpreview.github.io/?https://github.com/paymill/paymill-payment-form/blob/master/paymill_payment_sepa.html

always gives an error:

Please enter the account holder name.

**Comment by d0mme-zz** [comment]
@Iarwa1n or @tino-wittig, can you check this issue please?

**Comment by kazemek** [comment]
I will push a update in a few minutes.

**Comment by kazemek** [comment]
fixed.
