### ISSUE TITLE
Response for blacklisted accounts/ cards

### ISSUE THREAD

**Issue by d0mme-zz** [paymill/paymill-payment-form#18]
> The response for blacklisted accounts/card in the payment form is `unknown_error` but with this response merchant receives correct error.

Can you fix this error for our support team?

**Comment by enesf** [comment]
Stefan could you please take a look at this?

**Comment by enesf** [comment]
Reassigned to Thilo.

**Comment by enesf** [comment]
Reassigned to Stefan.

**Comment by Sharenkamp** [comment]
Hi d0mme,

the paymentform validation won't display blacklisted cards as invalid. In the next step it will try to create a transaction and the lib will return the correct errormessage.

please be sure to use the libs latest version: https://github.com/paymill/paymill-php

best regards
Stefan
