### ISSUE TITLE
Submitting form in demo mode

### ISSUE THREAD

**Issue by d0mme-zz** [paymill/paymill-payment-form#4]
After submitting form on demo mode (http://htmlpreview.github.io/?https://github.com/paymill/paymill-payment-form/blob/master/index.html) Nginx is throwing a "405 - not allowed".

Console:

<pre><code>Refused to execute script from 'https://raw.github.com/paymill/paymill-payment-form/master/js/vendor/modernizr-2.6.2.min.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled. htmlpreview.min.js:1

Refused to execute script from 'https://raw.github.com/paymill/paymill-payment-form/master/js/plugins.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled. htmlpreview.min.js:1

Refused to execute script from 'https://raw.github.com/paymill/paymill-payment-form/master/js/main.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled. htmlpreview.min.js:1

Uncaught TypeError: Cannot read property 'src' of null findblog.js:12</code></pre>

**Comment by d0mme-zz** [comment]
Forgot to mention system: Mac OSX (Version 10.8.3) , Chrome latest build (Version 27.0.1453.93)

**Comment by ghost** [comment]
The loading of the scripts doesn't work through raw.github.com, but there's a workaround, see "rawgithub.com". I've replaced the URL's and it works!
