### ISSUE TITLE
Form still not working

### ISSUE THREAD

**Issue by d0mme-zz** [paymill/paymill-payment-form#5]
Throwing an error in console and frontend.

Console:

<pre><code>21 : CS -> BG : FAILED rebuildcontextonload onloadwff.js:78
33 : CS -> BG : FAILED getprefs onloadwff.js:78</code></pre>

Frontend:

<pre><code>invalid_public_key</code></pre>

**Comment by ghost** [comment]
The form works, but the API key is not set. For testing purposes think we could make a form, to set the API key after page load. 
I can not reproduce your console output.

**Comment by d0mme-zz** [comment]
Ok, sorry about console output. That has been an previous error I didn't delete before sending form. Forget this, but yes:

> The form works, but the API key is not set. For testing purposes think we could make a form, to set the API key after > page load.

**Comment by d0mme-zz** [comment]
It's still not working with the test API keys, is it?

**Comment by ghost** [comment]
done
