### ISSUE TITLE
Test site only working with real public API keys?

### ISSUE THREAD

**Issue by d0mme-zz** [paymill/paymill-payment-form#8]
Is payment form http://htmlpreview.github.io/?https://github.com/paymill/paymill-payment-form/blob/master/index.html only working with real public API keys and should it be not having a standard key to see valid responses?

Right now it's only highlighting "unknown error"?

**Comment by ghost** [comment]
The form works only with real public API keys. By using the input field "Change Paymill Public API Key" you can set the public test API key. Right now it's only highlighting "unknown error", but then you will get real responses.

As i know we don't have standard keys and those which are provided with eg. paymill-php project were encrypted.
