### ISSUE TITLE
Catching Error Events in Request.php

### ISSUE THREAD

**Issue by matijajanc** [paymill/paymill-payment-form#9]
Hi,

Can you help me to set the error events in request.php? If something goes wrong and I get some error code back from paymill 40XXX or 50XXX that I catch them and redirect the customer to failure page.
Thanks.

**Comment by ghost** [comment]
Please provide us your example code as Gist, we need to know what exactly doesn't work for you. You can do that here, https://gist.github.com/ and paste the URL in this thread.

Then we'll take a look on that.

**Comment by matijajanc** [comment]
Link to my code https://gist.github.com/matijajanc/6406235

Thanks for any help.

**Comment by ghost** [comment]
Answer provided below the gist. https://gist.github.com/matijajanc/6406235
